//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUNGCAP
    {
        public int MACC { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> MADV { get; set; }
        public Nullable<int> MADAT { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual DAT DAT { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
