//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CUNGCAPs = new HashSet<CUNGCAP>();
            this.DATs = new HashSet<DAT>();
        }
    
        public int MANV { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string TENNV { get; set; }
        public string CCCD { get; set; }
        public Nullable<int> LOAINV { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public Nullable<int> LUONG { get; set; }
        public Nullable<System.DateTime> CHECKIN { get; set; }
        public Nullable<int> SONGAYLV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUNGCAP> CUNGCAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT> DATs { get; set; }
    }
}
